### ISSUE TITLE
Support reviewing the diff and staging only parts of a file

### ISSUE THREAD

**Issue by Pajn** [emaincourt/git-add-interactive#2]
It would be awesome if I could bring up the diff for the currently selected file. And while going though the diff it would be even more awesome if I could stage just the current chunk or line.

**Comment by emaincourt** [comment]
Hi @Pajn, I've been thinking for a long time about showing the diff of the files and it's definitely the next step on the roadmap. The second proposal would require a bit more work I think but I'll keep it in mind. It would actually be a nice feature !

**Comment by Pajn** [comment]
Yeah, those two are pretty big each one on their own so this should probably be split.

Maybe something like https://github.com/so-fancy/diff-so-fancy could be used to show the diff in a nice way, but with that it may be even harder to stage a specific chunk as we would need to figure out the correct lines from the diff.

**Comment by emaincourt** [comment]
Hi @Pajn, I've added a first draft of the `diff` feature. Not the ability to stage lines yet. I've been looking around for something more pretty than the original `git diff` but sadly I think users would need to globally install any other package to do so (e.g. `diff-so-fancy`)
